vis1_description = "Explore the standout performers of EURO 2020 with our comprehensive visualizations. Our Total Goals by Team Bar Chart provides a clear comparison of team performance by showing the total number of goals each team scored throughout the tournament. Dive deeper with the Average Goals by Team Bar Chart, which offers insights into the consistency of each team's scoring abilities across matches. Complementing these, the Total Goals per Team per Match Heatmap visualizes the goals scored by each team in every match, allowing for a detailed comparison of match-by-match performance."
vis1_notice = "NOTE: There is a loading time of approximately 4 seconds (varying depending the CPU performance) when alternating between Total and Average Goals"

vis2_vis3_description = "Uncover the tactical maneuvers of teams in EURO 2020 with our Bi-Directional Bar Chart. This visualization highlights the top five significant events from each match, based on detailed analysis. By showing the frequency distributions of these events, you can gain a deeper understanding of the strategic approaches taken by the teams. You can also delve into the critical moments of each rounds between specific countries. Using our Event Distribution Chart, you can pinpoint the specific tactics that led to the winning team's victory."
vis4_description = "Discover the teams with the best offensive and defensive balance in EURO 2020 using our Goal Difference by Country Bar Chart. This chart provides a straightforward visual representation of each team's goal difference, helping you quickly identify the top-performing teams."
vis4_notice = "NOTE: Select the Countries in the legend in order to filter them out of the visualization"

vis5_description = "Relive the most thrilling matches of EURO 2020 with our Top Matches by Total Goals Scored Horizontal Bar Chart. This visualization highlights the games where teams scored the most goals, showcasing the tournament's most exciting moments."
vis6_description = "Analyze the win-loss records of EURO 2020 teams with our Win-Loss Record Bar Chart. Each team is represented with two bars, one for wins and one for losses, providing a clear comparison of their performance throughout the tournament."
vis6_notice = "NOTE: Select the elements (Wins or Losses) in the legend to filter them out of the visualization"

vis7_description = "Understand the outcomes of EURO 2020 matches with our Percentage of Match Outcomes Pie Chart. This chart breaks down the percentage of matches that ended in a win, draw, or loss for the home team, providing a clear overview of home team performances.."
vis8_description = "Explore the dynamics of match events with our Event Occurrences Per Time Interval Heatmap. This heatmap visualizes the frequency of different match events over various time periods, helping you identify trends and patterns throughout the tournament."
match_comp_description = "A Visualization of Gaming Results"
